### ISSUE TITLE
repo-Umzug: privat? Organization "Hafis"?

### ISSUE THREAD

**Issue by meisl** [chdoerr/Hafis-Homepage#32]
Aus Besprechung am 17.11.2018, chdoerr & meisl @ Mariandl:

Der status quo - Hafis-repo ist öffentlich und "gehört" meisl - ist nicht optimal.
* ein Transfer zu einem anderen Account ist relativ einfach. Issues und Wiki kann man mitnehmen: https://help.github.com/en/articles/transferring-a-repository
* kostenlos sind nur öffentliche repos
* Vorteil von privatem repo: könnte auch sensitive Daten wie insbes. Arbeitsdateien für die Übungshefte ("Mein fabelhaftes Deutschheft") enthalten*
* ein sog. "Developer"-Account (für Einzelperson) kostet 7$/Monat und erlaubt private repos (beliebig viele), und man kann "collaborators" ernennen. Das wäre so wie jetzt auch, nur dass das repo privat wäre.
* ein sog. "Team"-Account beinhaltet private repos und
  - erlaubt die Einrichtung einer "organization" (hier: Hafis) mit Mitgliedern
  - es gibt verschiedene Rollen mit unterschiedlichen Rechten: owner, admin, member, u.ä.
  - kostet ab 25$/Monat für die ersten 5 Mitglieder, und 9$/Monat je weiteres Mitglied
* Bezahlung: paypal
* Zum Vergleich die Kosten bei 1&1/IONOS (alles brutto und pro Monat):
  - MyWebsite Basic: 9,99€
  - Zusatzdomain www.lernhilfe-hausaufgaben.de: 0,99€
  - Dual Basic (gekündigt zum 12.12.2018): gesamt 26,45€
     * Grundgebühr: 20,97€
     * MobileSiteBuilder: 2,99€
     * Virenscanner: 2,49€

Bewertung meinerseits:
* repo sollte auf jeden Fall entweder zu chdoerr oder neuer Organization Hafis transferiert werden
* privat sollte schon sein - 7$/Monat ist das sicher wert
* Organization Hafis wäre die passendste und schönste Lösung. Durch die Kündigung von 1&1 Dual Basic blieben die Kosten dabei etwa gleich.

Siehe:
* Bsp.-Organization wo ich Mitglied bin: [busterjs](https://github.com/busterjs) (schon länger her, momentan keine Aktivität)
* https://github.com/pricing
* https://help.github.com/categories/setting-up-and-managing-organizations-and-teams
* https://mein.ionos.de/subscriptions?filter.contract=any&filter.type=any (vorher einloggen)

___
* es ist wohl klar, dass es besser ist, alles - *wirklich* alles - in einem repo zu organisieren, oder? Ich sag nur: "Müsste noch auf irgendeinem Stick sein. Muss ich nur noch finden."...

**Comment by chdoerr** [comment]
Ja - sagen wir ab Januar-hat doch noch Zeit, oder?
Frage: Sind die Datenmengen der Hefte nicht zuviel?

**Comment by meisl** [comment]
Cool, dass Du das hier gleich gesehen hast!
Tatsächlich hatte ich Dich absichtlich nicht "assigned", und wollte Dich erst später damit behelligen... :)

Also ja: hat bis Januar Zeit.

Und ja: die Dateigrößen sind ein Problem. Die *gesamte* Größe des repos sollte für uns aber noch kein soo großes Problem sein. Einige GB sind für github nicht schlimm,  könnte halt nur ein wenig dauern, wenn man das repo komplett neu klont. Das macht man aber nicht wirklich oft.

Habe gesehen, dass github neuerdings "LFS", "Large-File-Support" bietet. Als "large" gelten Dateien über 100MB, und LFS läuft ein bisschen so, wie Du mir die riesigen pdfs über Google-Drive zugänglich gemacht hast: im repo wären nur spezielle "Links", die eigentlichen Daten wären in der Cloud. Muss ich mir noch genauer anschauen.
Ich denke aber, dass wir die Sache mit den Heften grundsätzlich anders angehen sollten:
* das Endprodukt (pdfs für Druckerei) ist sowieso zusammengesetzt/generiert - und wird NICHT im repo abgelegt
* stattdessen speichern wir die einzelnen Teile (in maximaler Qualität)
* ...sowie ein "Rezept" wie die Teile *zusammengesetzt* werden sollen. Das wäre
  - eine textuelle Beschreibung/Anleitung zum konkreten Vorgehen
  - und (idealerweise) eine Art Programm, das man einfach ausführt, um das Endprodukt automatisch zu generieren

Das sind aber bislang alles nur grobe Ideen.
Ob - und wenn ja, wie genau - das geht weiss ich noch nicht.

**Comment by meisl** [comment]
@chdoerr Die Arbeit an den Hafis-Heften schreitet voran - und ein privates repo, wo das alles hineinkommt, wird immer dringlicher. Warum bis Januar warten?

Also sagen wir mal so: wenn Du *uns* ein Weihnachtsgeschenk machen willst, dann wäre ein bezahlter github-Account mit privaten repos eine super Idee...
Am allerschönsten wäre ein Organization-Account "Hafis" :)  Details sh. OP; bzgl. Kündigungsfristen bin ich nicht ganz schlau geworden: vermute monatlich, schlimmstenfalls jährlich.

**Frage: Hast Du ein paypal-Konto?** Dann wär's nämlich "easy as pie".

Selbstverständlich würde ich anbieten, sämtliche Einrichtungen zu übernehmen. Falls Du einverstanden bist, bräuchte ich dafür die Zugangsdaten für Deinen github- sowie Deinen paypal-Account (natürlich *nicht hier, sondern eher telefonisch*).

**Comment by meisl** [comment]
@chdoerr: Glückwunsch zu Deinem neuen Dev-Account mit privaten repos!
Neben den Hafisheften gilt es jetzt
* dieses repo (`meisl/hafis` = hauptsächlich die Hafis-Website) zu Dir umzuziehen
* ...und #34 (Kruno-Sticks) anzugehen

### "Executive summary" ###
**Darf ich mich als `chdoerr` einloggen und ein wenig herumexperimentieren?**
Dein aktuelles Passwort kenne ich ja, aber natürlich mache ich das nicht ohne zu fragen.

### Erläuterung ###
Vor allem muss ich als `chdoerr` (Test-) repos anlegen (und nachher wieder löschen), sowie `meisl` entsprechende Rechte auf diese einräumen können.

#### Umzug zu chdoerr ####
Sollte eigentlich nur aus einem Klick auf "Transfer ownership" bestehen. **Aber** erstmal will ich das mit einem Test-repo durchspielen, denn
* ich hab's noch nie gemacht
* Issues und Wiki:
  - dürfen natürlich nicht verloren gehen
  - enthalten Links in das eigentlich repo (Bsp.: [`https://github.com/meisl/hafis/blob/master/README.md`](https://github.com/meisl/hafis/blob/master) ). Die müssen umgeschrieben werden, s.d. statt `meisl` dann `chdoerr` drin steht. Ich nehme stark an, dass das dann automatisch geschieht, bin mir aber nicht sicher.

#### Kruno-Sticks (#34) ####
Details dort, hier nur stichpunktartig die Hauptprobleme. Bei (der Lösung von) allen sollten wir die Features von git nutzen: Historie, Deduplikation.
Hauptprobleme:
* schiere Menge an Daten
* Duplikate:
  - nicht nur tauchen viele Dateien auf *beiden* Sticks auf (wenig verwunderlich)
  - sondern auch mehrfach auf *demselben* Stick (...)
* Archivierung/Dokumentation sowie sinnvolle Einordnung/Nachvollziehbarkeit

**Comment by chdoerr** [comment]
@meisl Wir gehen natürlich chronologisch vor und nehmen nur die Endfassungen.

**Comment by meisl** [comment]
@chdoerr bin nicht sicher, ob ich Dich richtig verstehe - nehme an, Du meinst (nur?) die Kruno-Sticks.

* Die Aufgabe besteht ja gerade darin, die Endfassungen zu *identifizieren*. Dafür hoffe ich Erstellungs- und Änderungsdatum verwenden zu können. **Aber:** auch die sind nicht wirklich verlässlich. Kommt drauf an, wie (womit) Kruno die Daten kopiert hat.
* Letztendlich ist der Begriff "obsolet" (Kruno: "Stick1 könnt ihr ignorieren") auch gar nicht rein objektiv zu fassen. Mein Ziel ist es, erstmal nach rein *objektiven* Kriterien (Bsp.: Dateien wirklich identisch), die zu beurteilende Datenmenge soweit wie möglich zu reduzieren. Und diese Reduktion soll diesmal komplett nachvollziehbar bzw. dokumentiert sein. Und ich kann versprechen, dass sich das lohnen wird. Aus den ca. 3 + 21 GB auf den vorliegenden Sticks werden so vmtl. zw. 10 und 15 GB werden.

Details zum procedere in #34.

**Comment by meisl** [comment]
Umzug von Test-repo **is da**:
https://github.com/meisl/repo-Umzug -> https://github.com/chdoerr/repo-Umzug

Analyse folgt.

**Comment by meisl** [comment]
Das hier können wir nicht schließen. Wir haben den Transfer noch nicht gemacht.

Die Analyse bin ich damals schuldig geblieben. I.W. lautet sie: "passt schon alles".
Die geänderten Links werden per Weiterleitung (redirect) gelöst (von github, automatisch).
Getestet ist das in dem Issue https://github.com/chdoerr/repo-Umzug/issues/2

Offen ist:
1. Was passiert, wenn ich nach dem Transfer wieder ein repo auf meinem Account namens `hafis` machen würde?
2. Dieses repo sollte besser `Hafis-Website` heißen statt `hafis`. Frage: *vor* oder *nach* dem Transfer umbenennen?

### Auf jeden Fall sollten wir den Transfer zusammen vor deinen Rechnern (!) machen
...denn die lokalen Klone müssen angepasst werden.

**Comment by meisl** [comment]
#### Zur Frage, ob *vorher* oder *nachher* umbenennen:
Ich sehe ein Argument für *vorher* (also: meisl/hafis -> meisl/Hafis-Website -> chdoerr/Hafis-Website), keines für *nachher*:
Es könnte sein, dass *du* irgendwann einmal ein repo namens "Hafis" machen willst - in welchem Fall es einen "clash" geben könnte, wenn wir *nach dem Transfer* umbenennen.

Mir persönlich reicht das für die Entscheidung pro *vorher umbenennen*.
Machen wir dann zu zweit, zusammen vor deinen Rechnern.

**Comment by meisl** [comment]
repo ist umbenannt in "Hafis-Homepage", ready for transfer.

Die lokalen Klone funktionieren erstmal weiterhin, muss man beizeiten aber 
- entweder neu klonen
- oder `.gitconfig` anpassen
